# Generated by Django 2.2 on 2020-08-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
