# Generated by Django 2.2 on 2020-09-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_app', '0003_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='numMooz',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
