# Generated by Django 2.2 on 2020-09-12 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boring_app', '0004_status_nummooz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Following'), (2, 'Blocked')])),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_users', to='boring_app.User')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_users', to='boring_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(related_name='related_to', through='boring_app.Relationship', to='boring_app.User'),
        ),
    ]
