# Generated by Django 2.2 on 2020-09-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_app', '0005_auto_20200912_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.IntegerField(choices=[(1, 'Following'), (2, 'Unfollowed')]),
        ),
    ]
