# Generated by Django 2.2 on 2020-09-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_app', '0006_auto_20200913_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
