# Generated by Django 2.2 on 2020-11-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_app', '0007_status_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='replies',
            field=models.ManyToManyField(related_name='reply', to='boring_app.Status'),
        ),
    ]
