# Generated by Django 2.2 on 2020-11-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_app', '0008_auto_20201119_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='isReply',
            field=models.BooleanField(default=False),
        ),
    ]
