# Generated by Django 2.2 on 2020-11-20 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boring_app', '0009_status_isreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='isReply',
        ),
        migrations.RemoveField(
            model_name='status',
            name='replies',
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('numReMooz', models.IntegerField(verbose_name=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Remooz', models.ManyToManyField(related_name='Replymooz', to='boring_app.User')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='boring_app.User')),
                ('repliedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='boring_app.Status')),
            ],
        ),
    ]
