# Generated by Django 2.2 on 2020-11-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_app', '0010_auto_20201120_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='proImage/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.CharField(default='description', max_length=255),
            preserve_default=False,
        ),
    ]
