# Generated by Django 2.2 on 2020-11-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_app', '0010_auto_20201120_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='proImage',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
