# Generated by Django 2.2 on 2020-11-24 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boring_app', '0012_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ProfilePic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro_pic', to='boring_app.ProImage'),
        ),
    ]
