# Generated by Django 2.2 on 2020-11-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_app', '0012_user_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='proImage',
            field=models.ImageField(blank=True, default='None', upload_to='profile_image'),
        ),
    ]
