# Generated by Django 2.2 on 2020-11-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_app', '0013_auto_20201123_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='proImage',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
