# Generated by Django 2.2 on 2020-11-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_app', '0015_auto_20201124_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proimage',
            name='uploader',
        ),
        migrations.AddField(
            model_name='user',
            name='proPicId',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
