# Generated by Django 2.2 on 2020-11-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_app', '0016_auto_20201124_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='proimage',
            name='example',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
