# Generated by Django 2.2 on 2020-11-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_app', '0018_remove_proimage_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='backImage/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='backPicId',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
