# Generated by Django 2.2 on 2020-12-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_app', '0020_auto_20201129_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fontColor',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fontSize',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fontStyle',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
