# Generated by Django 2.2 on 2020-12-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_app', '0021_auto_20201202_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fontStyle',
        ),
        migrations.AddField(
            model_name='user',
            name='fontType',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fontColor',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fontSize',
            field=models.IntegerField(default=2, null=True),
        ),
    ]
