# Generated by Django 2.2 on 2020-12-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring_app', '0022_auto_20201202_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fontColor',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fontSize',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fontType',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
